// src/app/(main)/deployments/components/deployment.tsx
import { toast } from "@/components/toast";
import { Button } from "@/components/ui/button";
import { Power, Settings } from "lucide-react";

export default function Deployment({ name, display_name, node, image, running }: { name: string; display_name: string; node: string; image: string, running?: boolean }) {
    async function powerAction() {
        if (running) {
            toast({
                title: "Stopping deployment...",
                description: `Scaling deployment "${name}" to 0 on node "${node}"`,
            })
        } else {
            toast({
                title: "Starting deployment...",
                description: `Scaling deployment "${name}" to 1 on node "${node}"`,
            })
        }
    }

    return (
        <div className="p-4 bg-card">
            <div className="flex flex-row items-center gap-2">
                {running ? (
                    <span className="size-3 block rounded-full bg-green-500" />
                ): (
                    <span className="size-3 block rounded-full bg-red-500" />
                )}
                <h2 className="text-xl font-semibold">{display_name}</h2>
            </div>
            <p className="text-muted-foreground text-sm overflow-hidden text-ellipsis whitespace-nowrap">Node: <span className="font-mono">{node}</span></p>
            <p className="text-muted-foreground text-sm overflow-hidden text-ellipsis whitespace-nowrap">Image: <span className="font-mono">{image}</span></p>
            <div className="flex flex-row mt-2 gap-2">
                <Button variant="outline" size="sm" onClick={powerAction}><Power /> {running ? "Stop" : "Start"}</Button>
                <Button variant="outline" size="sm"><Settings />Manage</Button>
            </div>
        </div>
    )
}

// src/lib/components/dashboard/deployment.svelte
<script lang="ts">
    import { Settings } from "lucide-svelte";
    let { name, image } = $props();
</script>

<div class="w-full border border-zinc-800 p-2 rounded-xl flex flex-row justify-between">
    <div>
        <h2 class="text-md font-bold">{name}</h2>
        <p class="text-sm font-mono overflow-hidden text-ellipsis whitespace-nowrap max-w-[16rem]">
            {image}
        </p>
    </div>
    <button class="flex items-center justify-center p-2 rounded-sm bg-zinc-800 border-zinc-700 border aspect-square hover:bg-zinc-700 hover:border-zinc-600 duration-100 cursor-pointer active:bg-zinc-600">
        <Settings />
    </button>
</div>
