// src/lib/components/formInput.svelte
<script lang="ts">
    let {
        label,
        id,
        placeholder,
        type = "text",
        required = false,
        value = $bindable("")
    }: {
        label: string,
        id: string,
        placeholder: string,
        type?: string,
        required?: boolean,
        value: string
    } = $props();
</script>

<div class="flex flex-col gap-2 w-full">
    <label for={id}>
        {label}
        {#if required} <span class="text-sm text-red-400">(required)</span> {/if}
    </label>
    <input
        type={type}
        id={id}
        placeholder={placeholder}
        class="p-2 rounded-xl border border-border text-white w-full focus:border-primary outline-none duration-200"
        bind:value={value}
        {required}
    />
</div>

// src/app/(main)/deployments/new/components/formInput.tsx
export default function FormInput({
    label,
    id,
    placeholder,
    type = "text",
    required = false,
    onChange,
    value,
}: {
    label: string;
    id: string;
    placeholder: string;
    type?: string;
    required?: boolean;
    onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    value?: string;
}) {
    return (
        <div className="flex flex-col gap-2">
            <label htmlFor={id}>
                {label} {required &&
                    <span className="text-sm text-red-400">(required)</span>
                }
            </label>
            <input
                type={type} 
                id={id}
                placeholder={placeholder} 
                className="p-2 rounded-md border border-zinc-800 text-white w-full focus:border-pink-500 outline-none duration-200" 
                onChange={onChange}
                required={required}
                value={value}
            />
        </div>
    )
}
