// src/components/toolbar.tsx
"use client";

import { Session, User } from "better-auth";
import { authClient } from "@/utils/auth-client";
import Navlink from "./navlink"
import { redirect } from "next/navigation";

export default function Toolbar({ session, user }: { session: Session, user: User }) {
    return (
        <div className="flex w-dvw flex-row items-center justify-between p-4 bg-zinc-950 border-b border-zinc-900">
            <div className="flex flex-row items-center gap-4">
                <h1 className="text-2xl font-bold">meownel</h1>
                <Navlink href="/dashboard" title="home"/>
                <Navlink href="/deployments" title="deployments"/>
            </div>
            <div className="hidden sm:flex flex-row items-center gap-4">
                <p className="text-sm text-zinc-400">Logged in as {user.name}</p>
                <div className="w-[1px] h-[32px] bg-zinc-800" />
                <button 
                    className="text-sm text-pink-500 hover:underline cursor-pointer"
                    onClick={async () => {
                        await authClient.signOut({
                            fetchOptions: {
                                onSuccess() {
                                    redirect("/");
                                }
                            }
                        });
                    }}
                >
                    Sign out
                </button>
            </div>
        </div>
    );
}

// src/lib/components/toolbar.svelte
<script lang="ts">
    import { authClient } from "$lib/auth-client";
    import type { PageProps } from "../../routes/$types";

    function onclick() {
        authClient.signOut({
            fetchOptions: {
                onSuccess() {
                    window.location.href = "/";
                }
            }
        });
    }

    const session = authClient.useSession();
</script>

<div class="flex w-dvw flex-row items-center justify-between p-4 bg-zinc-950 border-b border-zinc-900">
    <div class="flex flex-row items-center gap-4">
        <h1 class="text-2xl font-bold">meownel</h1>
        <a href="/dashboard" class="hover:border-b-4 border-pink-500 duration-150 text-lg">home</a>
        <a href="/deployments" class="hover:border-b-4 border-pink-500 duration-150 text-lg">deployments</a>
    </div>
    <div class="hidden sm:flex flex-row items-center gap-4">
        <p class="text-sm text-zinc-400">Logged in as {$session.data?.user.name}</p>
        <div class="w-px h-8 bg-zinc-800"></div>
        <button 
            class="text-sm text-pink-500 hover:underline cursor-pointer"
            {onclick}
        >
            Sign out
        </button>
    </div>
</div>
